package com.greylurk.randomizer;

import com.greylurk.randomizer.module.RollerModule;

import org.jooby.Jooby;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Jooby {
    Logger logger = LoggerFactory.getLogger(App.class);


    {
        use(new RollerModule());
        get("/", () -> "Hello World");

        onStart(() -> {
            logger.info("Starting up");
        });

        onStop(() -> {
            logger.info("Stopping");
        });

        onStarted(() -> {
            logger.info("Started");
        });
    }

    public static void main(final String[] args) {
        run(App::new, args);
    }
}
